// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWord.proto

package client.grpc.protobuf;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
