// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWord.proto

package client.grpc.protobuf;

public final class GrpcHelloProto {
  private GrpcHelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hello_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hello_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017helloWord.proto\022\005Hello\"\034\n\014HelloRequest" +
      "\022\014\n\004name\030\001 \001(\t\" \n\rHelloResponse\022\017\n\007messa" +
      "ge\030\001 \001(\t2@\n\005Hello\0227\n\010SayHello\022\023.Hello.He" +
      "lloRequest\032\024.Hello.HelloResponse\"\000B*\n\026co" +
      "m.ncst.grpc.protobufB\016GrpcHelloProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hello_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_Hello_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Hello_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hello_HelloResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
